services:
  - type: pserv
    name: cafeteria-db
    plan: free

  - type: web
    name: cafeteria-backend
    runtime: node
    plan: free
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          name: cafeteria-db
          type: pserv
          property: connectionString

  - type: web
    name: cafeteria-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://cafeteria-backend.onrender.com/api
