services:
  # PostgreSQL (não colocar runtime nem startCommand)
  - type: pserv
    name: cafeteria-db
    plan: free

  # Backend Node.js
  - type: web
    name: cafeteria-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromService:
          name: cafeteria-db
          type: pserv
          property: internalConnectionString
    rootDir: backend

  # Frontend React
  - type: web
    name: cafeteria-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    rootDir: frontend
